### ISSUE TITLE
GET /users?

### ISSUE THREAD

**Issue by cchurness** [stratosphererl/stratosphere#113]
# Acceptance Criteria
- [x] Given an application with this endpoint exists
- [x] When a GET request is made at this endpoint
- [x] Then all of the user data for all users is returned
- [x] And when the request is made with search parameters
- [x] Then a list of replays that match the parameters is returned

# Notes
## Search parameters
- Username
- Platform
- Date profile was created
- Number of users to return
- Possibly a sort-by parameter

**Comment by chrishollandaise** [comment]
It might be helpful to include some query parameters here to add additional functionality. Filtering users by platform, ranks, etc might be nice here.

Also, pagination might be nice because if we had a million users, we wouldn't want to return a million users as a result. So, you would effectively want additional parameters for the page, and the amount of users you want to return (with a max)
